# The configuration parameters below are used for HDAAGT model training and evaluation.
model_name: "HDAAGT"

# Model Architecture parameters
hidden_size: 512
n_heads: 4
Nusers: 32 # This is the number of users in the dataset for Graph Attention
Nnodes: 32 # This should be the same as Nusers
concat: False

# Dataset parameters
Headers: ['Frame', 'ID', 'BBx', 'BBy','W', 'L' , 'Cls','Tr1', 'Tr2', 'Tr3', 'Tr4', 'Zone', 'Xreal', 'Yreal']
Columns_to_keep: [11,2,3,7,8,9,10] #['Zone','BBx', 'BBy','Tr1', 'Tr2', 'Tr3', 'Tr4']
Embedding Dict_size: [12, 1024, 1024, 9,9,9,9] # size of the Embedding for ['Zone','BBx', 'BBy','Tr1', 'Tr2', 'Tr3', 'Tr4']
xy_indx: [1, 2] # the index of x and y  of the Columns_to_Keep used for speed calculation function
Columns_to_Predict: [0,1] #['BBx', 'BBy'] The columns we expect to predict
NZones: 10
NTrfL: 4
sl: 30 # sequence length
future: 30 # future prediction horizon
sw: 2 # sliding window for preparation of the dataset
sn: 10 # 
Centre: [512,512] # The centre of the image
dssc: 2 # we can downsample the sequence length (or scene) by this factor
dstar: 2 # we can downsample the future prediction horizon( or target) by this factor
noise_multiply: 10 
noise_amp: 4 # pixels
ratio: 0.6 # probability of the noise


# Startup parameters
sos: [10,1016,1016,7,7,7,7] # , torch.zeros(17))).repeat(1,1,32, 1).to(device), this is the start of the sequence
eos: [11,1020,1020,8,8,8,8] #), torch.zeros(17))).repeat(1,1,32, 1).to(device), this is the end of the sequence
csvpath: '/RawData/TrfZonXYCam.csv'
Zoneconf_path: '/utilz/ZoneConf.yaml'
generate_data: true #  Add class by loading the CSV file
test_in_epoch: true # It's for testing the model in each epoch
model_from_scratch: true # It's for creating model from scratch
Train: true # It's for training the model with the prepared data
only_test: false # If we only want to test the model, there is no need to process the training data


# Training parameters
learning_rate: 4e-4
schd_stepzise: 25
gamma: 0.15
epochs: 350
patience_limit: 50
clip: 0.25
batch_size: 32